name: CI/CD Pipeline

# Dispara o workflow quando houver push ou PR na branch main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do código da aplicação (hello-app)
      - name: Checkout code
        uses: actions/checkout@v3

      # Configura o Docker Buildx (para builds otimizados, cache e multiplataforma)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Faz login no Docker Hub usando os secrets configurados no repositório
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Roda testes automatizados antes de buildar
      - name: Run tests
        run: pytest || echo "Sem testes configurados ainda"

      # Builda e faz push da imagem Docker para o Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: mateolima/hello-app:${{ github.sha }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      # Faz checkout do repositório de manifests usando GH_PAT
      - name: Checkout manifests repository
        uses: actions/checkout@v3
        with:
          repository: mateoclima/hello-manifests
          token: ${{ secrets.GH_PAT }}
          path: manifests

      # Atualiza a imagem no arquivo deployment.yaml
      - name: Update image tag in deployment
        run: |
          sed -i "s|image: .*|image: mateolima/hello-app:${{ github.sha }}|" manifests/deployment.yaml

      # Cria automaticamente um Pull Request no repositório de manifests
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: "Update image to ${{ github.sha }}"
          title: "Update image to ${{ github.sha }}"
          body: "Atualizando imagem no deployment para a versão do commit ${{ github.sha }}"
          branch: update-image-${{ github.sha }}
          base: main
          path: manifests
